# Generated by Django 3.0 on 2022-12-01 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_personinfo_vocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocation',
            name='name',
        ),
        migrations.DeleteModel(
            name='PersonInfo',
        ),
        migrations.DeleteModel(
            name='Vocation',
        ),
    ]
