# Generated by Django 4.1.3 on 2022-11-26 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_is_md'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_md',
        ),
    ]
