# Generated by Django 2.2.8 on 2022-11-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, 'HTML'), (2, '最新文章'), (3, '最热文章'), (4, '最近评论'), (5, '博主列表')], default=1, verbose_name='展示类型'),
        ),
    ]
